name: Build and Deploy

on:
  push:
    branches:
      - prod

jobs:
  building-pipeline:
    name: ${{ github.ref }} building
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.9.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Use node version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version}}
          cache: "pnpm"

      - run: pnpm install
      - run: |
          echo "${{ secrets.PROD_ENV }}">.env
      - run: pnpm run build
      - name: Set environment variables
        run: |
          if [ "${{ github.ref }}" == "refs/heads/prod" ]; then
          echo "HOST_IP=${{ secrets.HOST_IP }}" >> $GITHUB_ENV
          echo "HOST_USERNAME=${{ secrets.HOST_USERNAME }}" >> $GITHUB_ENV
          echo "HOST_PORT=3001" >> $GITHUB_ENV
          echo "APP_NAME=re-latido-prod" >> $GITHUB_ENV
          echo "HOST_SSH_KEY<<EOF" >> $GITHUB_ENV
          echo "${{ secrets.HOST_SSH_KEY }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          fi

      - name: rsync deployments
        uses: burnett01/rsync-deployments@master
        with:
          switches: -avzr --delete
          path: ./
          remote_path: /home/ubuntu/re-latido-test/
          remote_host: ${{ env.HOST_IP }}
          remote_user: ${{ env.HOST_USERNAME }}
          remote_key: ${{ env.HOST_SSH_KEY }}

      - name: Start pm2 using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST_IP }}
          username: ${{ env.HOST_USERNAME }}
          key: ${{ env.HOST_SSH_KEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /home/ubuntu/"${{ env.APP_NAME }}"/
            pm2 delete "${{ env.APP_NAME }}"
            pm2 start npm --name "${{ env.APP_NAME }}" -- start --port "${{ env.HOST_PORT }}"
            pm2 save
